// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/delivery_metric.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/delivery_metric.go -destination=internal/domain/mocks/mock_delivery_metric.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bse/notifyd/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryMetricRepository is a mock of DeliveryMetricRepository interface.
type MockDeliveryMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliveryMetricRepositoryMockRecorder is the mock recorder for MockDeliveryMetricRepository.
type MockDeliveryMetricRepositoryMockRecorder struct {
	mock *MockDeliveryMetricRepository
}

// NewMockDeliveryMetricRepository creates a new mock instance.
func NewMockDeliveryMetricRepository(ctrl *gomock.Controller) *MockDeliveryMetricRepository {
	mock := &MockDeliveryMetricRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryMetricRepository) EXPECT() *MockDeliveryMetricRepositoryMockRecorder {
	return m.recorder
}

// GetByNotificationID mocks base method.
func (m *MockDeliveryMetricRepository) GetByNotificationID(ctx context.Context, notificationID uuid.UUID) (*domain.DeliveryMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNotificationID", ctx, notificationID)
	ret0, _ := ret[0].(*domain.DeliveryMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNotificationID indicates an expected call of GetByNotificationID.
func (mr *MockDeliveryMetricRepositoryMockRecorder) GetByNotificationID(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNotificationID", reflect.TypeOf((*MockDeliveryMetricRepository)(nil).GetByNotificationID), ctx, notificationID)
}

// Upsert mocks base method.
func (m_2 *MockDeliveryMetricRepository) Upsert(ctx context.Context, m *domain.DeliveryMetric) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Upsert", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDeliveryMetricRepositoryMockRecorder) Upsert(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDeliveryMetricRepository)(nil).Upsert), ctx, m)
}
