// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/webhook_endpoint.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/webhook_endpoint.go -destination=internal/domain/mocks/mock_webhook_endpoint.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bse/notifyd/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookEndpointRepository is a mock of WebhookEndpointRepository interface.
type MockWebhookEndpointRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookEndpointRepositoryMockRecorder
	isgomock struct{}
}

// MockWebhookEndpointRepositoryMockRecorder is the mock recorder for MockWebhookEndpointRepository.
type MockWebhookEndpointRepositoryMockRecorder struct {
	mock *MockWebhookEndpointRepository
}

// NewMockWebhookEndpointRepository creates a new mock instance.
func NewMockWebhookEndpointRepository(ctrl *gomock.Controller) *MockWebhookEndpointRepository {
	mock := &MockWebhookEndpointRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookEndpointRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookEndpointRepository) EXPECT() *MockWebhookEndpointRepositoryMockRecorder {
	return m.recorder
}

// CreateWithinLimit mocks base method.
func (m *MockWebhookEndpointRepository) CreateWithinLimit(ctx context.Context, e *domain.WebhookEndpoint, limit int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithinLimit", ctx, e, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithinLimit indicates an expected call of CreateWithinLimit.
func (mr *MockWebhookEndpointRepositoryMockRecorder) CreateWithinLimit(ctx, e, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithinLimit", reflect.TypeOf((*MockWebhookEndpointRepository)(nil).CreateWithinLimit), ctx, e, limit)
}

// Delete mocks base method.
func (m *MockWebhookEndpointRepository) Delete(ctx context.Context, id, tenantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebhookEndpointRepositoryMockRecorder) Delete(ctx, id, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebhookEndpointRepository)(nil).Delete), ctx, id, tenantID)
}

// GetByID mocks base method.
func (m *MockWebhookEndpointRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.WebhookEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.WebhookEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWebhookEndpointRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWebhookEndpointRepository)(nil).GetByID), ctx, id)
}

// ListActiveByTenantAndEvent mocks base method.
func (m *MockWebhookEndpointRepository) ListActiveByTenantAndEvent(ctx context.Context, tenantID uuid.UUID, eventType domain.WebhookEventType) ([]*domain.WebhookEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByTenantAndEvent", ctx, tenantID, eventType)
	ret0, _ := ret[0].([]*domain.WebhookEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByTenantAndEvent indicates an expected call of ListActiveByTenantAndEvent.
func (mr *MockWebhookEndpointRepositoryMockRecorder) ListActiveByTenantAndEvent(ctx, tenantID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByTenantAndEvent", reflect.TypeOf((*MockWebhookEndpointRepository)(nil).ListActiveByTenantAndEvent), ctx, tenantID, eventType)
}

// ListByTenant mocks base method.
func (m *MockWebhookEndpointRepository) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]*domain.WebhookEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]*domain.WebhookEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockWebhookEndpointRepositoryMockRecorder) ListByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockWebhookEndpointRepository)(nil).ListByTenant), ctx, tenantID)
}

// Update mocks base method.
func (m *MockWebhookEndpointRepository) Update(ctx context.Context, id, tenantID uuid.UUID, input domain.UpdateWebhookEndpointInput) (*domain.WebhookEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, tenantID, input)
	ret0, _ := ret[0].(*domain.WebhookEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWebhookEndpointRepositoryMockRecorder) Update(ctx, id, tenantID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebhookEndpointRepository)(nil).Update), ctx, id, tenantID, input)
}
