// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/channel.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/channel.go -destination=internal/domain/mocks/mock_channel.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bse/notifyd/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelConfigRepository is a mock of ChannelConfigRepository interface.
type MockChannelConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChannelConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockChannelConfigRepositoryMockRecorder is the mock recorder for MockChannelConfigRepository.
type MockChannelConfigRepositoryMockRecorder struct {
	mock *MockChannelConfigRepository
}

// NewMockChannelConfigRepository creates a new mock instance.
func NewMockChannelConfigRepository(ctrl *gomock.Controller) *MockChannelConfigRepository {
	mock := &MockChannelConfigRepository{ctrl: ctrl}
	mock.recorder = &MockChannelConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelConfigRepository) EXPECT() *MockChannelConfigRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChannelConfigRepository) Create(ctx context.Context, cfg *domain.ChannelConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockChannelConfigRepositoryMockRecorder) Create(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChannelConfigRepository)(nil).Create), ctx, cfg)
}

// Delete mocks base method.
func (m *MockChannelConfigRepository) Delete(ctx context.Context, id, tenantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChannelConfigRepositoryMockRecorder) Delete(ctx, id, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChannelConfigRepository)(nil).Delete), ctx, id, tenantID)
}

// GetByID mocks base method.
func (m *MockChannelConfigRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.ChannelConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.ChannelConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockChannelConfigRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockChannelConfigRepository)(nil).GetByID), ctx, id)
}

// ListByTenant mocks base method.
func (m *MockChannelConfigRepository) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]*domain.ChannelConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]*domain.ChannelConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockChannelConfigRepositoryMockRecorder) ListByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockChannelConfigRepository)(nil).ListByTenant), ctx, tenantID)
}

// ListByTenantAndChannel mocks base method.
func (m *MockChannelConfigRepository) ListByTenantAndChannel(ctx context.Context, tenantID uuid.UUID, ch domain.ChannelType) ([]*domain.ChannelConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantAndChannel", ctx, tenantID, ch)
	ret0, _ := ret[0].([]*domain.ChannelConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenantAndChannel indicates an expected call of ListByTenantAndChannel.
func (mr *MockChannelConfigRepositoryMockRecorder) ListByTenantAndChannel(ctx, tenantID, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantAndChannel", reflect.TypeOf((*MockChannelConfigRepository)(nil).ListByTenantAndChannel), ctx, tenantID, ch)
}

// Update mocks base method.
func (m *MockChannelConfigRepository) Update(ctx context.Context, id, tenantID uuid.UUID, input domain.UpdateChannelConfigInput) (*domain.ChannelConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, tenantID, input)
	ret0, _ := ret[0].(*domain.ChannelConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockChannelConfigRepositoryMockRecorder) Update(ctx, id, tenantID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChannelConfigRepository)(nil).Update), ctx, id, tenantID, input)
}
