// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/notification.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/notification.go -destination=internal/domain/mocks/mock_notification.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/bse/notifyd/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// DeleteOlderThan mocks base method.
func (m *MockNotificationRepository) DeleteOlderThan(ctx context.Context, tenantID uuid.UUID, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, tenantID, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockNotificationRepositoryMockRecorder) DeleteOlderThan(ctx, tenantID, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockNotificationRepository)(nil).DeleteOlderThan), ctx, tenantID, cutoff)
}

// CountByStatus mocks base method.
func (m *MockNotificationRepository) CountByStatus(ctx context.Context) (map[domain.NotificationStatus]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx)
	ret0, _ := ret[0].(map[domain.NotificationStatus]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockNotificationRepositoryMockRecorder) CountByStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockNotificationRepository)(nil).CountByStatus), ctx)
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, n)
}

// GetByID mocks base method.
func (m *MockNotificationRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationRepository)(nil).GetByID), ctx, id)
}

// IncrementRetry mocks base method.
func (m *MockNotificationRepository) IncrementRetry(ctx context.Context, id uuid.UUID, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetry", ctx, id, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetry indicates an expected call of IncrementRetry.
func (mr *MockNotificationRepositoryMockRecorder) IncrementRetry(ctx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetry", reflect.TypeOf((*MockNotificationRepository)(nil).IncrementRetry), ctx, id, lastError)
}

// List mocks base method.
func (m *MockNotificationRepository) List(ctx context.Context, filter domain.NotificationFilter) ([]*domain.Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockNotificationRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationRepository)(nil).List), ctx, filter)
}

// MarkDelivered mocks base method.
func (m *MockNotificationRepository) MarkDelivered(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelivered", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDelivered indicates an expected call of MarkDelivered.
func (mr *MockNotificationRepositoryMockRecorder) MarkDelivered(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelivered", reflect.TypeOf((*MockNotificationRepository)(nil).MarkDelivered), ctx, id)
}

// SetAsynqTaskID mocks base method.
func (m *MockNotificationRepository) SetAsynqTaskID(ctx context.Context, id uuid.UUID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAsynqTaskID", ctx, id, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAsynqTaskID indicates an expected call of SetAsynqTaskID.
func (mr *MockNotificationRepositoryMockRecorder) SetAsynqTaskID(ctx, id, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAsynqTaskID", reflect.TypeOf((*MockNotificationRepository)(nil).SetAsynqTaskID), ctx, id, taskID)
}

// SetProviderMsgID mocks base method.
func (m *MockNotificationRepository) SetProviderMsgID(ctx context.Context, id uuid.UUID, providerMsgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderMsgID", ctx, id, providerMsgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProviderMsgID indicates an expected call of SetProviderMsgID.
func (mr *MockNotificationRepositoryMockRecorder) SetProviderMsgID(ctx, id, providerMsgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderMsgID", reflect.TypeOf((*MockNotificationRepository)(nil).SetProviderMsgID), ctx, id, providerMsgID)
}

// UsageByTenant mocks base method.
func (m *MockNotificationRepository) UsageByTenant(ctx context.Context, tenantID uuid.UUID, from, to time.Time) (*domain.UsageReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsageByTenant", ctx, tenantID, from, to)
	ret0, _ := ret[0].(*domain.UsageReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsageByTenant indicates an expected call of UsageByTenant.
func (mr *MockNotificationRepositoryMockRecorder) UsageByTenant(ctx, tenantID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsageByTenant", reflect.TypeOf((*MockNotificationRepository)(nil).UsageByTenant), ctx, tenantID, from, to)
}

// UpdateStatus mocks base method.
func (m *MockNotificationRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.NotificationStatus, lastError *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationRepositoryMockRecorder) UpdateStatus(ctx, id, status, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateStatus), ctx, id, status, lastError)
}
