// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/delivery_attempt.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/delivery_attempt.go -destination=internal/domain/mocks/mock_delivery_attempt.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bse/notifyd/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryAttemptRepository is a mock of DeliveryAttemptRepository interface.
type MockDeliveryAttemptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryAttemptRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliveryAttemptRepositoryMockRecorder is the mock recorder for MockDeliveryAttemptRepository.
type MockDeliveryAttemptRepositoryMockRecorder struct {
	mock *MockDeliveryAttemptRepository
}

// NewMockDeliveryAttemptRepository creates a new mock instance.
func NewMockDeliveryAttemptRepository(ctrl *gomock.Controller) *MockDeliveryAttemptRepository {
	mock := &MockDeliveryAttemptRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryAttemptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryAttemptRepository) EXPECT() *MockDeliveryAttemptRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeliveryAttemptRepository) Create(ctx context.Context, a *domain.DeliveryAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeliveryAttemptRepositoryMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliveryAttemptRepository)(nil).Create), ctx, a)
}

// ListByNotification mocks base method.
func (m *MockDeliveryAttemptRepository) ListByNotification(ctx context.Context, notificationID uuid.UUID) ([]*domain.DeliveryAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNotification", ctx, notificationID)
	ret0, _ := ret[0].([]*domain.DeliveryAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNotification indicates an expected call of ListByNotification.
func (mr *MockDeliveryAttemptRepositoryMockRecorder) ListByNotification(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNotification", reflect.TypeOf((*MockDeliveryAttemptRepository)(nil).ListByNotification), ctx, notificationID)
}
