package domain

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// WebhookEventType identifies the kind of status event a webhook endpoint can
// subscribe to. Only the two terminal notification outcomes are offered —
// intermediate states like "processing" or "retrying" are noise a receiver
// cannot act on differently from waiting for the terminal event.
type WebhookEventType string

const (
	WebhookEventDelivered WebhookEventType = "notification.delivered"
	WebhookEventFailed    WebhookEventType = "notification.failed"
)

func validWebhookEventTypes() []WebhookEventType {
	return []WebhookEventType{WebhookEventDelivered, WebhookEventFailed}
}

func IsValidWebhookEventType(t WebhookEventType) bool {
	for _, valid := range validWebhookEventTypes() {
		if t == valid {
			return true
		}
	}
	return false
}

// ValidateWebhookEvents checks that events is non-empty, every entry is a
// recognised WebhookEventType, and no entry repeats. It accepts []string
// (rather than []WebhookEventType) because that is the shape both the JSON
// request body and the TEXT[] database column naturally decode into.
func ValidateWebhookEvents(events []string) error {
	if len(events) == 0 {
		return fmt.Errorf("%w: events must not be empty", ErrValidationFailed)
	}

	seen := make(map[string]bool, len(events))
	for _, event := range events {
		if !IsValidWebhookEventType(WebhookEventType(event)) {
			return fmt.Errorf("%w: invalid event type: %s", ErrValidationFailed, event)
		}
		if seen[event] {
			return fmt.Errorf("%w: duplicate event type: %s", ErrValidationFailed, event)
		}
		seen[event] = true
	}
	return nil
}

// WebhookEndpoint is a tenant-configured destination for delivery-status
// events. The secret is generated by notifyd at creation time and returned
// to the caller exactly once (see service.WebhookService.Create) — it is
// never included in any subsequent read.
type WebhookEndpoint struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	URL       string    `json:"url"`
	Secret    string    `json:"-"`
	Events    []string  `json:"events"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

// SubscribesTo reports whether this endpoint should receive the given event
// type. Inactive endpoints never match, regardless of their events list.
func (e *WebhookEndpoint) SubscribesTo(eventType WebhookEventType) bool {
	if !e.IsActive {
		return false
	}
	for _, event := range e.Events {
		if event == string(eventType) {
			return true
		}
	}
	return false
}

type CreateWebhookEndpointInput struct {
	URL    string   `json:"url"`
	Events []string `json:"events"`
}

type UpdateWebhookEndpointInput struct {
	URL      *string  `json:"url,omitempty"`
	Events   []string `json:"events,omitempty"`
	IsActive *bool    `json:"is_active,omitempty"`
}

type WebhookEndpointRepository interface {
	// CreateWithinLimit atomically creates e if the tenant's endpoint count
	// is below limit, returning ErrWebhookLimitReached otherwise — mirrors
	// APIKeyRepository.CreateWithinLimit's per-tenant cap pattern.
	CreateWithinLimit(ctx context.Context, e *WebhookEndpoint, limit int) error
	GetByID(ctx context.Context, id uuid.UUID) (*WebhookEndpoint, error)
	ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]*WebhookEndpoint, error)
	// ListActiveByTenantAndEvent returns active endpoints subscribed to
	// eventType, used by the dispatcher to fan out one task per endpoint.
	ListActiveByTenantAndEvent(ctx context.Context, tenantID uuid.UUID, eventType WebhookEventType) ([]*WebhookEndpoint, error)
	Update(ctx context.Context, id, tenantID uuid.UUID, input UpdateWebhookEndpointInput) (*WebhookEndpoint, error)
	Delete(ctx context.Context, id, tenantID uuid.UUID) error
}
